[package]
name = "learn_cargo"
version = "0.1.0"
authors = ["hulunhao <hulunhao@bytedance.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
